### ISSUE TITLE
resolving "Pelargonium × hortorum" causes exceptions/ errors

### ISSUE THREAD

**Issue by jhpoelen** [GlobalNamesArchitecture/gnresolver#107]
When resolving "Pelargonium × hortorum" using http://resolver.globalnames.org, the following error page is shown: ```We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly.```

Original errors where observed when resolving names using the resolver api. Other examples include: Citrus × paradisi, Acer × freemanii, Malus ×domestica, Abelia × grandiflora, and Platanus × acerifolia.

**Comment by alexander-myltsev** [comment]
This is not the issue of `gnresolver`. @dimus , would you figure out where to put it best?

**Comment by dimus** [comment]
Yes, I'm moving it to gni. May be it is better to wait with this one until we have gnresolver running. @jhpoelen , how important it is for you?

We do not deal with hybrids in gnresolver yet as well :-/

**Comment by dimus** [comment]
Issue moved to [GlobalNamesArchitecture/gni #55](https://github.com/GlobalNamesArchitecture/gni/issues/55) via [**ZenHub**](https://www.zenhub.com/)
