### ISSUE TITLE
Design feature list to cover functionality of GN resolver and parser

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnresolver#23]
- [x] estimate complexity

**Comment by dimus** [comment]
- Working API which covers existing functionality of GNI and resolver
- Working GUI which covers existing functionality of GNI and resolver
- Reasonable scoring algorithm
- Performance and load analysis with known numbers, possible optimization
- "Faceted" search
- Migrated most recent data from database
