### ISSUE TITLE
suggest to include fishbase_taxon_cache as name source

### ISSUE THREAD

**Issue by jhpoelen** [GlobalNamesArchitecture/gnresolver#52]
as discussed with @dimus @alexander-myltsev last wk, I've created a project https://github.com/jhpoelen/fishbase_taxon_cache that generates a fishbase taxon cache that contains all species accessible through sealifebase.org and fishbase.org . Please let me know if there's anything I can do to help include the full taxonomic paths of this resource into global names. I am hoping to start using this data source through your name resolver.

**Comment by alexander-myltsev** [comment]
Thanks 👍

**Comment by jhpoelen** [comment]
@dimus thanks for adding the name source 177 Taxon Cache. I've created a first integration with it.  Two suggestions: (a) populate the taxon path ids, as far as I can tell the taxon path is populated, but somehow the ids are lost. (b) include a pointer to https://github.com/jhpoelen/fishbase_taxon_cache in source description. This way, the user of the name source can figure out how the names were collected.

If these are too much trouble, please feel free to close the issue.
