### ISSUE TITLE
Successful name_strings search results always have type Fuzzy(0)

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnresolver#62]
We probably should not have Fuzzy search kind at all for name_strings search matching.

Currently we have searches like

http://gnresolver.globalnames.org/api/name_strings?search_term=Pardosa%20moesta

having "Fuzzy(0)" for all the results
```
{
nameString: {
name: {
id: "b18f184f-1d46-572d-90ee-bb4f3687ea57",
value: "Pardosa moesta Kaston, 1948"
},
canonicalName: {
id: "aefc0ec7-f875-5b83-9cb7-ff71cc790994",
value: "Pardosa moesta"
}
},
dataSourceId: 169,
kind: "Fuzzy(0)"
}
```

**Comment by alexander-myltsev** [comment]
Resolved by a020160538c932fb336a7973a37c89f5da6e5192
