### ISSUE TITLE
As a user of crossmap I need to be able to do crossmap from several sources

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnresolver#70]
We need our system to support more than one source for crossmapping. When people do crossmap -- they enter

- resolution data source (Open tree, or Encyclopedia of life)
- original data source (which has local ids)
- target data source
- one or several local IDs from original data source (probably we can make limit pretty high 50k?)

output is IDs from target data source

As a first step we do not support jumping from one  resolution source to another, it is a future user story.

**Comment by dimus** [comment]
cross_maps table should have the following fields:

data_source_id | name_string_id | taxon_id | cm_data_source_id | cm_local_id

(data_source_id, name_string_id, taxon_id) form a composite primary key and are identical to the key from name_string_indices. The order in the key is important. Number of composite keys for open_tree_taxonomy should be the same in composite_maps and in name_string_indices.

we can try to make a "search" key as a composite key as well -- (cm_local_id, cm_data_source_id, data_source_id)

**Comment by alexander-myltsev** [comment]
Hm, can it be -- two local ids for the same `data_source_id, name_string_id, taxon_id`:

```
179	00026087-718e-5616-97f2-9e3780ff3f7c	578296	11	29
179	00026087-718e-5616-97f2-9e3780ff3f7c	578296	11	302
```

**Comment by dimus** [comment]
If homonyms are not resolved -- it might happen
